# Generated by Django 4.0.6 on 2022-08-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('price', models.IntegerField(max_length=300)),
                ('desc', models.CharField(max_length=300)),
                ('pro_image', models.ImageField(upload_to='upload/')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook.category')),
            ],
        ),
    ]
